package webm

import (
	"bytes"
	"context"
	"encoding/base64"
	"math"
	"os"
	"testing"

	"github.com/famomatic/puremux/internal/core"
)

// TestDemuxReaderLibwebmDiscardPadding uses the WebM project's own libwebm
// golden file (testing/testdata/discard_padding.webm, commit 9299bbb6). The
// fixture was produced by mkvmuxer and is intentionally not generated by this
// implementation. Its three BlockGroups carry signed DiscardPadding values
// 12810000, 127, and -128 as asserted by libwebm's parser tests.
func TestDemuxReaderLibwebmDiscardPadding(t *testing.T) {
	encoded, err := os.ReadFile("testdata/libwebm_discard_padding.webm.b64")
	if err != nil {
		t.Fatal(err)
	}
	data, err := base64.StdEncoding.DecodeString(string(bytes.TrimSpace(encoded)))
	if err != nil {
		t.Fatal(err)
	}
	rd, err := NewDemuxReader(bytes.NewReader(data))
	if err != nil {
		t.Fatalf("NewDemuxReader: %v", err)
	}
	meta := rd.Metadata()
	if meta.DocType != "webm" || meta.TimestampScaleNS != 1_000_000 {
		t.Fatalf("metadata = %+v", meta)
	}
	tracks := rd.Tracks()
	if len(tracks) != 1 || tracks[0].Codec != core.CodecOpus || tracks[0].Channels != 2 || tracks[0].Name != "unit_test" {
		t.Fatalf("tracks = %+v", tracks)
	}
	wantPadding := []int64{12_810_000, 127, -128}
	for i, want := range wantPadding {
		pkt, err := rd.NextPacket(context.Background())
		if err != nil {
			t.Fatalf("packet %d: %v", i, err)
		}
		if pkt.DiscardPaddingNS != want || !pkt.Keyframe || len(pkt.Data) != 10 {
			t.Fatalf("packet %d = %+v, want padding %d, key, 10 bytes", i, pkt, want)
		}
	}
}

func TestDemuxReaderCanceledAndMalformed(t *testing.T) {
	ctx, cancel := context.WithCancel(context.Background())
	cancel()
	// A valid reader is required to reach the per-read cancellation check.
	encoded, err := os.ReadFile("testdata/libwebm_discard_padding.webm.b64")
	if err != nil {
		t.Fatal(err)
	}
	data, _ := base64.StdEncoding.DecodeString(string(bytes.TrimSpace(encoded)))
	rd, err := NewDemuxReader(bytes.NewReader(data))
	if err != nil {
		t.Fatal(err)
	}
	if _, err := rd.NextPacket(ctx); err != context.Canceled {
		t.Fatalf("canceled read error = %v", err)
	}
	for i, bad := range [][]byte{nil, {0x1a}, {0x1a, 0x45, 0xdf, 0xa3, 0xff}} {
		if _, err := NewDemuxReader(bytes.NewReader(bad)); err == nil {
			t.Errorf("malformed case %d accepted", i)
		}
	}
}

func TestQueueBlockTimestampAdditionBoundary(t *testing.T) {
	// RFC 9559 Block fields are MSB-first/big-endian: 0x81 is track VINT 1,
	// 00 01 is signed relative timecode +1, 0x80 marks a key SimpleBlock,
	// and the final opaque byte is the single VP8 frame payload.
	block := []byte{0x81, 0x00, 0x01, 0x80, 0x00}
	newReader := func(clusterTicks uint64) *DemuxReader {
		return &DemuxReader{
			clusterTicks: clusterTicks,
			metadata:     DemuxMetadata{TimestampScaleNS: 1},
			trackMap: map[int]*DemuxTrack{
				1: {Number: 1, Codec: core.CodecVP8, IsVideo: true},
			},
		}
	}

	overflow := newReader(math.MaxInt64)
	if err := overflow.queueBlock(block, 0, true, 1, 0, false); err == nil {
		t.Fatal("cluster timestamp plus relative timecode overflow was accepted")
	}
	if len(overflow.pending) != 0 {
		t.Fatal("overflowing block queued a packet")
	}

	boundary := newReader(math.MaxInt64 - 2)
	if err := boundary.queueBlock(block, 0, true, 1, 0, false); err != nil {
		t.Fatalf("valid timestamp boundary rejected: %v", err)
	}
	if len(boundary.pending) != 1 || boundary.pending[0].TimestampNS != math.MaxInt64-1 ||
		boundary.pending[0].DurationNS != 1 {
		t.Fatalf("boundary packet = %+v", boundary.pending)
	}
}
