package mp4

import (
	"bytes"
	"encoding/binary"
	"errors"
	"io"
	"testing"
)

// --- spec-derived MP4 box builders (ISO/IEC 14496-12) ---
//
// Every box is [size:4 BE][type:4][payload]. The test composes minimal boxes
// by hand so the byte values are spec-accurate, not generated by a library.

// box builds a box: 4-byte BE size + 4-byte type + payload.
func mkBox(typ string, payload []byte) []byte {
	b := make([]byte, 8+len(payload))
	binary.BigEndian.PutUint32(b[0:4], uint32(len(b)))
	copy(b[4:8], typ)
	copy(b[8:], payload)
	return b
}

// ftyp payload: major brand(4) + minor version(4) + compat brands(4..).
func ftypPayload() []byte {
	p := make([]byte, 8)
	copy(p[0:4], "isom")                      // major brand
	binary.BigEndian.PutUint32(p[4:8], 0x200) // minor version
	p = append(p, "isom"...)                  // compatible brand
	return p
}

// mvhd v0 payload (after version/flags):
//
//	creation(4) modification(4) timescale(4) duration(4) + rest zero-padded.
//
// We only need timescale; the reader discards the rest.
func mvhdPayload() []byte {
	p := make([]byte, 100)                    // full v0 mvhd is 96 bytes; pad is harmless
	binary.BigEndian.PutUint32(p[8:12], 1000) // timescale=1000
	return p
}

// mdhd v0 payload (after version/flags): creation(4) modification(4)
// timescale(4) duration(4) + language(2)+predefined(2).
func mdhdPayload(timescale uint32) []byte {
	// v0 mdhd body (after version/flags): creation(4)+modification(4)+
	// timescale(4)+duration(4)+language(2)+predefined(2) = 20 bytes.
	p := make([]byte, 20)
	binary.BigEndian.PutUint32(p[8:12], timescale)
	return p
}

// tkhd v0 payload: version/flags handled outside; pad a minimal body.
func tkhdPayload() []byte { return make([]byte, 80) }

// stsd payload (WITHOUT the fullBox version/flags prefix, which fullBox adds):
// entry_count(4) + one sample entry. Sample entry: size(4)+type(4)+reserved(6)+
// data_ref_index(2). We emit a minimal 16-byte entry so the reader can read
// the type at offset 4 of the entry.
func stsdPayload(entryType string) []byte {
	p := make([]byte, 4)
	binary.BigEndian.PutUint32(p[0:4], 1) // entry_count = 1
	se := make([]byte, 16)
	binary.BigEndian.PutUint32(se[0:4], 16)
	copy(se[4:8], entryType)
	p = append(p, se...)
	return p
}

// stts payload: version(1)+flags(3)+count(4) + entries[count](8).
func sttsPayload(entries []sttsEntry) []byte {
	p := make([]byte, 4)
	binary.BigEndian.PutUint32(p[0:4], uint32(len(entries)))
	for _, e := range entries {
		row := make([]byte, 8)
		binary.BigEndian.PutUint32(row[0:4], e.count)
		binary.BigEndian.PutUint32(row[4:8], e.delta)
		p = append(p, row...)
	}
	return p
}

// stsz payload: version(1)+flags(3)+uniform(4)+count(4)+sizes[count](4).
func stszPayload(sizes []uint32) []byte {
	p := make([]byte, 8)
	binary.BigEndian.PutUint32(p[0:4], 0)                  // uniform = 0
	binary.BigEndian.PutUint32(p[4:8], uint32(len(sizes))) // count
	for _, s := range sizes {
		row := make([]byte, 4)
		binary.BigEndian.PutUint32(row, s)
		p = append(p, row...)
	}
	return p
}

// stsc payload: version(1)+flags(3)+count(4)+entries[count](12).
func stscPayload(entries []stscEntry) []byte {
	p := make([]byte, 4)
	binary.BigEndian.PutUint32(p[0:4], uint32(len(entries)))
	for _, e := range entries {
		row := make([]byte, 12)
		binary.BigEndian.PutUint32(row[0:4], e.firstChunk)
		binary.BigEndian.PutUint32(row[4:8], e.samplesPerChunk)
		binary.BigEndian.PutUint32(row[8:12], e.sampleDescIndex)
		p = append(p, row...)
	}
	return p
}

// stco payload: version(1)+flags(3)+count(4)+offsets[count](4).
func stcoPayload(offsets []uint32) []byte {
	p := make([]byte, 4)
	binary.BigEndian.PutUint32(p[0:4], uint32(len(offsets)))
	for _, o := range offsets {
		row := make([]byte, 4)
		binary.BigEndian.PutUint32(row, o)
		p = append(p, row...)
	}
	return p
}

// stss payload: version(1)+flags(3)+count(4)+sample_nums[count](4).
func stssPayload(nums []uint32) []byte {
	p := make([]byte, 4)
	binary.BigEndian.PutUint32(p[0:4], uint32(len(nums)))
	for _, n := range nums {
		row := make([]byte, 4)
		binary.BigEndian.PutUint32(row, n)
		p = append(p, row...)
	}
	return p
}

// fullBox prepends version(1)+flags(3) to the payload and wraps in a box.
func fullBox(typ string, payload []byte) []byte {
	hdr := make([]byte, 4) // version=0, flags=0
	return mkBox(typ, append(hdr, payload...))
}

// buildTrak assembles a trak box for one track.
func buildTrak(entryType string, timescale uint32, stts []sttsEntry, sizes []uint32, stsc []stscEntry, stco []uint32, stss []uint32) []byte {
	stblChildren := bytes.Join([][]byte{
		fullBox("stsd", stsdPayload(entryType)),
		fullBox("stts", sttsPayload(stts)),
		fullBox("stsz", stszPayload(sizes)),
		fullBox("stsc", stscPayload(stsc)),
		fullBox("stco", stcoPayload(stco)),
		fullBox("stss", stssPayload(stss)),
	}, nil)
	stbl := mkBox("stbl", stblChildren)
	minf := mkBox("minf", stbl)
	mdhd := fullBox("mdhd", mdhdPayload(timescale))
	mdia := mkBox("mdia", bytes.Join([][]byte{mdhd, minf}, nil))
	tkhd := fullBox("tkhd", tkhdPayload())
	return mkBox("trak", bytes.Join([][]byte{tkhd, mdia}, nil))
}

// buildMP4 composes a minimal MP4 with the given tracks + mdat payload.
// buildMP4 composes ftyp+moov+mdat and returns the bytes plus the absolute
// byte offset of the mdat payload (just past the mdat box header), so callers
// can set stco/co64 chunk offsets precisely (bytes.Index would false-match
// "mdat" sequences inside moov).
func buildMP4(traks [][]byte, mdatPayload []byte) ([]byte, int) {
	var out bytes.Buffer
	out.Write(mkBox("ftyp", ftypPayload()))
	mvhd := fullBox("mvhd", mvhdPayload())
	moov := mkBox("moov", bytes.Join(append([][]byte{mvhd}, traks...), nil))
	out.Write(moov)
	mdatPayloadOff := out.Len() + 8 // +8 for the mdat box header
	out.Write(mkBox("mdat", mdatPayload))
	return out.Bytes(), mdatPayloadOff
}

func TestNewReaderNonSeekable(t *testing.T) {
	r := bytes.NewReader([]byte{0, 0, 0, 8, 'f', 't', 'y', 'p'})
	_, err := NewReader(r)
	// bytes.Reader IS a ReadSeeker, so this should not fail on seekability.
	// It will fail on corruption instead. Use a non-seeker to test the gate.
	nonSeek := struct{ io.Reader }{r}
	_, err = NewReader(nonSeek)
	if !errors.Is(err, ErrNotSeekable) {
		t.Errorf("non-seekable input: got %v want ErrNotSeekable", err)
	}
}

func TestNewReaderCorrupt(t *testing.T) {
	// Valid ftyp but no moov.
	data := mkBox("ftyp", ftypPayload())
	_, err := NewReader(bytes.NewReader(data))
	if !errors.Is(err, ErrCorrupt) {
		t.Errorf("corrupt (no moov): got %v want ErrCorrupt", err)
	}
}

func TestNewReaderEmpty(t *testing.T) {
	_, err := NewReader(bytes.NewReader(nil))
	if !errors.Is(err, ErrCorrupt) && !errors.Is(err, io.EOF) && err == nil {
		t.Errorf("empty input: got %v want ErrCorrupt or EOF", err)
	}
}

func TestReaderVP9Track(t *testing.T) {
	// One VP9 video track: 2 samples, timescale 1000 (1ms/unit),
	// sample durations [33,33] ms, sizes [10,10], one chunk, sample 1 = keyframe.
	sizes := []uint32{10, 10}
	stts := []sttsEntry{{count: 2, delta: 33}}
	stsc := []stscEntry{{firstChunk: 1, samplesPerChunk: 2}}
	stss := []uint32{1}
	// First build with a 1-entry placeholder stco so the moov size matches the
	// final build (stco entry count, not value, determines moov length).
	trak := buildTrak("vp09", 1000, stts, sizes, stsc, []uint32{0}, stss)
	mdatPayload := make([]byte, 20)
	for i := range mdatPayload {
		mdatPayload[i] = byte(i + 1) // 1..20
	}
	data, mdatPayloadOff := buildMP4([][]byte{trak}, mdatPayload)
	stco := []uint32{uint32(mdatPayloadOff)}
	trak = buildTrak("vp09", 1000, stts, sizes, stsc, stco, stss)
	data, _ = buildMP4([][]byte{trak}, mdatPayload)

	rd, err := NewReader(bytes.NewReader(data))
	if err != nil {
		t.Fatalf("NewReader: %v", err)
	}
	tracks := rd.Tracks()
	if len(tracks) != 1 {
		t.Fatalf("got %d tracks want 1", len(tracks))
	}
	// codecFromSampleEntry maps "vp09" -> CodecVP9.
	if tracks[0].Codec.String() != "vp9" {
		t.Errorf("codec = %s want vp9", tracks[0].Codec)
	}
	if !tracks[0].IsVideo {
		t.Error("expected video track")
	}

	// Sample 1: absMs 0, keyframe, offset->bytes 1..10.
	s1, err := rd.NextSample()
	if err != nil {
		t.Fatalf("NextSample 1: %v", err)
	}
	if s1.AbsMs != 0 {
		t.Errorf("s1 absMs = %d want 0", s1.AbsMs)
	}
	if !s1.Keyframe {
		t.Error("s1 should be keyframe")
	}
	if !bytes.Equal(s1.Data, mdatPayload[0:10]) {
		t.Errorf("s1 data = %v want %v", s1.Data, mdatPayload[0:10])
	}
	// Sample 2: absMs 33, not keyframe, offset->bytes 11..20.
	s2, err := rd.NextSample()
	if err != nil {
		t.Fatalf("NextSample 2: %v", err)
	}
	if s2.AbsMs != 33 {
		t.Errorf("s2 absMs = %d want 33", s2.AbsMs)
	}
	if s2.Keyframe {
		t.Error("s2 should not be keyframe")
	}
	if !bytes.Equal(s2.Data, mdatPayload[10:20]) {
		t.Errorf("s2 data = %v want %v", s2.Data, mdatPayload[10:20])
	}
	// EOF.
	if _, err := rd.NextSample(); err != io.EOF {
		t.Errorf("expected EOF, got %v", err)
	}
}

func TestReaderTwoTracksMergedOrder(t *testing.T) {
	// Video (VP9) sample at 0ms, audio (Opus) sample at 5ms. Merge order must
	// be video-first.
	vSizes := []uint32{4}
	vStts := []sttsEntry{{count: 1, delta: 33}}
	vStsc := []stscEntry{{firstChunk: 1, samplesPerChunk: 1}}
	vStss := []uint32{1}
	aSizes := []uint32{4}
	aStts := []sttsEntry{{count: 1, delta: 20}}
	aStsc := []stscEntry{{firstChunk: 1, samplesPerChunk: 1}}
	mdatPayload := []byte{0xAA, 0xAA, 0xAA, 0xAA, 0xBB, 0xBB, 0xBB, 0xBB}
	vTrak := buildTrak("vp09", 1000, vStts, vSizes, vStsc, nil, vStss)
	aTrak := buildTrak("Opus", 1000, aStts, aSizes, aStsc, nil, nil)
	data, mdatPayloadOff := buildMP4([][]byte{vTrak, aTrak}, mdatPayload)
	off := uint32(mdatPayloadOff)
	vTrak = buildTrak("vp09", 1000, vStts, vSizes, vStsc, []uint32{off}, vStss)
	aTrak = buildTrak("Opus", 1000, aStts, aSizes, aStsc, []uint32{off + 4}, nil)
	data, _ = buildMP4([][]byte{vTrak, aTrak}, mdatPayload)

	rd, err := NewReader(bytes.NewReader(data))
	if err != nil {
		t.Fatalf("NewReader: %v", err)
	}
	if len(rd.Tracks()) != 2 {
		t.Fatalf("got %d tracks want 2", len(rd.Tracks()))
	}
	// First emitted sample must be the video keyframe (0ms < 5ms).
	s, err := rd.NextSample()
	if err != nil {
		t.Fatal(err)
	}
	if !s.Keyframe {
		t.Error("first merged sample should be the video keyframe")
	}
	if s.AbsMs != 0 {
		t.Errorf("first absMs = %d want 0", s.AbsMs)
	}
	// Second must be audio.
	s2, err := rd.NextSample()
	if err != nil {
		t.Fatal(err)
	}
	if s2.AbsMs != 0 {
		t.Errorf("second absMs = %d want 0 (first audio sample)", s2.AbsMs)
	}
}

func TestReaderCo64(t *testing.T) {
	// VP9-like track using co64 (64-bit chunk offsets) instead of stco.
	sizes := []uint32{4}
	stts := []sttsEntry{{count: 1, delta: 33}}
	stsc := []stscEntry{{firstChunk: 1, samplesPerChunk: 1}}
	stss := []uint32{1}
	mdatPayload := []byte{0xCC, 0xCC, 0xCC, 0xCC}

	buildTrack := func(co64Off uint64) []byte {
		stblChildren := bytes.Join([][]byte{
			fullBox("stsd", stsdPayload("av01")),
			fullBox("stts", sttsPayload(stts)),
			fullBox("stsz", stszPayload(sizes)),
			fullBox("stsc", stscPayload(stsc)),
			co64Box([]uint64{co64Off}),
			fullBox("stss", stssPayload(stss)),
		}, nil)
		stbl := mkBox("stbl", stblChildren)
		minf := mkBox("minf", stbl)
		mdhd := fullBox("mdhd", mdhdPayload(1000))
		mdia := mkBox("mdia", bytes.Join([][]byte{mdhd, minf}, nil))
		tkhd := fullBox("tkhd", tkhdPayload())
		return mkBox("trak", bytes.Join([][]byte{tkhd, mdia}, nil))
	}
	// First build with offset 0 to discover the mdat payload position. The
	// trak size is independent of the co64 offset value (both 8 bytes), so the
	// mdat position is stable across rebuilds.
	data, mdatPayloadOff := buildMP4([][]byte{buildTrack(0)}, mdatPayload)
	data, _ = buildMP4([][]byte{buildTrack(uint64(mdatPayloadOff))}, mdatPayload)

	rd, err := NewReader(bytes.NewReader(data))
	if err != nil {
		t.Fatalf("NewReader: %v", err)
	}
	if rd.Tracks()[0].Codec.String() != "av1" {
		t.Errorf("codec = %s want av1", rd.Tracks()[0].Codec)
	}
	s, err := rd.NextSample()
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.Equal(s.Data, mdatPayload) {
		t.Errorf("co64 data = %v want %v", s.Data, mdatPayload)
	}
}

// co64Box builds a co64 box: version/flags + count + 8-byte offsets.
func co64Box(offsets []uint64) []byte {
	p := make([]byte, 8)
	binary.BigEndian.PutUint32(p[4:8], uint32(len(offsets)))
	for _, o := range offsets {
		row := make([]byte, 8)
		binary.BigEndian.PutUint64(row, o)
		p = append(p, row...)
	}
	return fullBox("co64", p[4:]) // fullBox prepends version/flags
}
